---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-demo
  labels:
    name: opentelemetry-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-raw
  namespace: opentelemetry-demo
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: petclinic
      name: petclinic
    spec:
      containers:
        - image: public.ecr.aws/sumologic/opentelemetry-petclinic:latest
          imagePullPolicy: Always
          name: petclinic
          resources:
      hostname: petclinic
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  namespace: opentelemetry-demo
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - name: "http-petclinic"
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}
